insert into PARAMETRO(TIPO_DOCUMENTO, TEMPO_RETENCAO) values(1, 120);
insert into PARAMETRO(TIPO_DOCUMENTO, TEMPO_RETENCAO) values(2, 60);
insert into PARAMETRO(TIPO_DOCUMENTO, TEMPO_RETENCAO) values(3, 30);
insert into PARAMETRO(TIPO_DOCUMENTO, TEMPO_RETENCAO) values(4, 45);