CREATE TABLE DOCUMENTO( 
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SISTEMA INT NOT NULL,
    TIPO_DOCUMENTO INT NOT NULL,
    DATA_DOCUMENTO BIGINT NOT NULL,
    NOME VARCHAR NOT NULL,
    CAMINHO VARCHAR NOT NULL,
    DELETADO BOOLEAN
)
;
    
CREATE TABLE PARAMETRO( 
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_DOCUMENTO INT NOT NULL,
    TEMPO_RETENCAO BIGINT NOT NULL
)
;
