CREATE TABLE COMPRA( 
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR BIGINT NOT NULL,
    ITENS BIGINT NOT NULL,
    STATUS VARCHAR NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE PAGAMENTO( 
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_COMPRA INT,
    BANDEIRA VARCHAR NOT NULL,
    PARCELAS INT NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
;


